### ISSUE TITLE
sound

### ISSUE THREAD

**Issue by eastealswallets** [28klotlucas2/Mario64webgl#1]
theres no sound

**Comment by slambo311** [comment]
This is literally a port of Mario 64, I don't think copyright's a problem.

**Comment by 28klotlucas2** [comment]
You have to click on the game for sound to play. It's a browser issue.

**Comment by 28klotlucas2** [comment]
If it still dosen't work go to site settings and change sound from auto to allow.

**Comment by shaunlebron** [comment]
yeah I had to manually allow sound permission on chrome://settings/content/sound, and in safari under settings > websites > auto-play
