### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by George42009** [28klotlucas2/Mario64webgl#4]
So exactly how did you manage to port Super Mario 64 to WebGL and then port it to a website? I just want to know so I can try it myself with some other games.

**Comment by TheRealDigitalMaster** [comment]
People do not know this, but it is illegal. Nintendo does not allow people to torrent their games and play them for free. I might report this to the police soon.

**Comment by TheRealDigitalMaster** [comment]
*not you, the person who ported it

**Comment by George42009** [comment]
> People do not know this, but it is illegal. Nintendo does not allow people to torrent their games and play them for free. I might report this to the police soon.

Nobody cares, they hardly even enforce it except by taking it down. Now if it really lost them money as if it was a more recent game, they would most definitely get it involved in court.

**Comment by TheRealDigitalMaster** [comment]
It is still a copyright issue, and it is still law.

**Comment by George42009** [comment]
> It is still a copyright issue, and it is still law.

Also, why do you have to whine about it and report it to the police as if it's hurting you. What do you get out of that?

**Comment by TheRealDigitalMaster** [comment]
Satisfaction of knowing that the torrented version of Nintendo's game is deleted.

**Comment by slambo311** [comment]
Let's be real, torrents are not the problem here. I doubt anybody uses torrents anymore. Modern pirates just send that crap through a .zip, .7z, or .rar. Also, the game was released in 1996, so Nintendo can barely do a goddamn thing. There's practically millions of Mario 64 roms floating around on the internet, in plain sight.

**Comment by slambo311** [comment]
Nintendo hasn't done crap to the Mario 64 modding community in years. Also, as long as it's not public like this one, it is perfectly legal. The way that it's turned into a website, you require a legally obtained Mario 64 rom, the stuff used to do it doesn't provide any Nintendo assets.

**Comment by slambo311** [comment]
So in conclusion, do your research.

**Comment by slambo311** [comment]
Now to answer the main question, I believe it uses the Mario 64 decompilation.
